### ISSUE TITLE
Export other data than MS

### ISSUE THREAD

**Issue by Adafede** [compomics/ThermoRawFileParserGUI#1]
Hi, since you were so amazingly reactive with solutions last time, I'll give it a try:

Could you find a way to also export other types of data from the .raw? (UV, Light Scattering, CAD, ...)

For UV (2D data), the export in .netCDF from Waters works fine, for 1D data like Corona CAD and so on, maybe an additional CSV would be great.

Thanks and good evening

**Comment by hbarsnes** [comment]
I do not really see how this question is linked with the ThermoRawFileParserGUI? Which is simply a wrapper for the [ThermoRawFileParser](https://github.com/compomics/ThermoRawFileParser), and I'm not even sure if the question is relevant there either..? But if you think it is, I recommend that you ask the question [there](https://github.com/compomics/ThermoRawFileParser/issues) instead?
