### ISSUE TITLE
How to run the GUI?

### ISSUE THREAD

**Issue by enryH** [compomics/ThermoRawFileParserGUI#3]
Hey. Could you state briefly how to run the GUI? I can see that the `cmd`-program is working (I can see the help etc), but as I am not familiar with Java, I wonder if I have to start it from the Java Runtime Environment or if I just need to "click" the correct sub-file?

I am currently on Windows 10.

Best, Henry

**Comment by hbarsnes** [comment]
Hi Henry,

If you have Java installed, all you need to do is double-click the file called ThermoRawFileParserGUI-1.7.0.jar. You can also start it from the command line via `java -jar ThermoRawFileParserGUI-1.7.0.jar`.

Best regards,
Harald

**Comment by enryH** [comment]
Thanks Harald... I found my mistake. Somehow I managed to click on the wrong link in the readme (I guess the "releases" instead of the jpg)... I found the .jar file now!
