### ISSUE TITLE
Download button does not work in Edge and Chrome

### ISSUE THREAD

**Issue by caetera** [compomics/ThermoRawFileParserGUI#4]
Hi @hbarsnes, 
I have a weird issue to report. The download button the front page does not seem to work in Edge and Chrome. They complain that the download is insecure and refuse to proceed. Here is the what Edge provides as an explanation - https://docs.microsoft.com/en-us/DeployEdge/edge-learnmore-mixed-content-downloads . Firefox, however, just does not seem to care much about it (i.e. it works fine). The direct download link, i.e. the one pointing to http://genesis.ugent.be does seem to work fine in all browsers. My guess is that the problem is "unsecure" http link, on a "secure" https github page. Maybe the simplest workaround would be to provide a direct link in text, or mention something like "copy this link to a new browser window, if download fails"

**Comment by hbarsnes** [comment]
@caetera Yes, I started noticing this myself last week as well. The same happens for all our tools. I have not been able to come up with a good workaround though. Perhaps the only real fix is to change the downloads from http to https (i.e. changing http://genesis.ugent.be/maven2 to https://genesis.ugent.be/maven2)? Not sure of that is feasible though.

Note however that the download works fine if done via http://compomics.github.io/projects/ThermoRawFileParserGUI (as then both the page and the download is http).

**Comment by caetera** [comment]
@hbarsnes Edge does "upgrade" the connection to https on github.io though, i.e. when accessing http://compomics.github.io/projects/ThermoRawFileParserGUI, it redirects immediately to https://compomics.github.io/projects/ThermoRawFileParserGUI (Cannot confirm with Chrome now).
I agree, the clear solution is, likely, to move genesis.ugent.be/maven2 to https; but, maybe, the quick (and dirty) workaround is to ask users to open the download link explicitly (i.e. not by clicking but by pasting to the address bar).

**Comment by hbarsnes** [comment]
We have started looking into moving genesis.ugent.be/maven2 to https (which is also needed for other reasons). Hopefully this will shortly solve the problem.

**Comment by caetera** [comment]
Wow! That is a neat solution!

**Comment by hbarsnes** [comment]
Genesis has now been moved to https and the download button should work again. :)
