### ISSUE TITLE
Precursor list of MS3 scan does not seem right

### ISSUE THREAD

**Issue by fcyu** [compomics/ThermoRawFileParserGUI#5]
I converted a Thermo raw file into mzML format. It is from SPS-MS3. In the precursor list, the MS2 one is correct, but the MS1 one misses some fields, and the  `selected ion m/z` does not have enough decimal points. I don't have permission to share the data, but you should be able to reproduce it using any SPS-MS3 data.

Please feel free to let me know if you cannot reproduce this issue.

Please also feel free to transfer this issue to somewhere else if I am reporting it to a wrong repo.

Thanks,

Fengchao

**Comment by hbarsnes** [comment]
Hi Fengchao,

ThermoRawFileParserGUI is simply a graphical user interface for [ThermoRawFileParser](https://github.com/compomics/ThermoRawFileParser). I would therefore recommend that you ask the same question in their issue tracker instead: https://github.com/compomics/ThermoRawFileParser/issues.

If any changes are made and a new version of ThermoRawFileParser is released, we will update the version in ThermoRawFileParserGUI accordingly.

Best regards,
Harald

**Comment by yhsongk** [comment]
I can not find in the resources folder the file qExactive01819.raw. I would like to test out the program Peak-List-Generation. Thanks for the help!

**Comment by hbarsnes** [comment]
@yhsongk The raw file qExactive01819.raw is just an example raw file and is not included with [ThermoRawFileParserGUI](https://github.com/compomics/ThermoRawFileParserGUI). You may however find that particular raw file here: https://drive.google.com/file/d/0B4sW8rLWPbRyZXFyTG80LUxTMTQ/view?usp=sharing&resourcekey=0-QQiPYjXAt5ORtWCrfuwWIA.
